### ISSUE TITLE
Forget to reset form and close page after creating paper

### ISSUE THREAD

**Issue by AsyncFox** [SMS-COSMO/SMS-Tree#5]
## Bug details

- 管理页面论文创建成功之后没有reset form和关闭页面
- 离开时还会显示修改未提交（其实已经创建成功）

**Comment by ZTL-UwU** [comment]
fixed by:
a3233831341e35114b0d8fedf7d21d1e846bfce6
01aa90a864399d293f9be1cc93ed47fc1a61e378
